XcodeMLtoCXX/test/Makefile
テストが落ちたときに変換元のXcodeMLファイル見られないの不便なので残す(makeがビルド終了後に中間ファイル削除するのを阻止する)ようにしました。
=> Improve Makefile

XcodeMLtoCXX/src/TypeAnalyzer.cpp
*  `unsigned_int` に対応
*  アンダースコア(`_`)を含むデータ型識別名をそのまま型名としてC++ソースコードに出力していたのを修正
=> Fix data type identifiers of fundamental type (<basicType>)

XcodeMLtoCXX/src/TypeAnalyzer.cpp, XcodeMLtoCXX/src/XcodeMlType.cpp, XcodeMLtoCXX/src/XcodeMlType.h
<arrayType>要素が、その`elemType`属性の指すデータ型定義要素より先に現れていた場合に異常終了するバグを修正しました。
=> Keep arrayTypeProc from std::out_of_range

docs/XcodeML_CXX.md
少なくとも次のミーティングまではopenのままにしておいてください。
暗黙の型変換を表現する `<implicitCastExpr>` 要素を追加
=> Add `<implicitCastExpr>` element to XcodeML/C++ spec

CXXtoXML/src/TypeTableInfo.cpp
#59 のバグによりデータ型定義要素が子要素を持たないようになってしまいました。このPRはTypeTableInfoを修正し、次の要素が子要素を持つようにします。
* functionType
* unionType
* structType
* classType
* enumType
=> Add child elements to data type definition elements

CXXtoXML/src/TypeTableInfo.cpp
* クラスをTypeTableInfoに登録する際に自分自身を構成要素に含む型を持つメンバー(例: クラス`A`のメンバー関数`void memfun(const A&)`)があると不正終了する問題を修正
* `<constructor>`要素と`<destrutor>`要素に対応
=> Fix CXXtoXML

CXXtoXML/tests/CppTest/Makefile
Change file generation order in `make check` in CXXtoXML/tests/CppTest/Makefile.
=> Don't create *.xml files first on `make check`

CXXtoXML/src/DeclarationsVisitor.cpp, CXXtoXML/src/DeclarationsVisitor.h, CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, CXXtoXML/src/XSLTs/add_symbols_elem.xsl, XcodeMLtoCXX/src/CodeBuilder.cpp
* 正変換のバグ修正(f27191e)
* CXXtoXMLがclangConstructorInitializer要素を出力するようにした
* メンバー関数に対して適用しているXSLT templateをコンストラクター・デストラクターにも適用した
* 逆変換でコンストラクターに対応するための準備をした
=> Add support for constructor / destructor declarations to CXXtoXML(and XSLT)

XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/XcodeMlType.cpp, XcodeMLtoCXX/src/XcodeMlType.h
clang::FunctionTypeはコンストラクター・デストラクターの返り値型をvoid型としているため、逆変換の際に不適切な宣言を出力してしまう。例:
```
class A {
void A(int i, int j){
}
};
```
そこで、Function::makeDeclarationWithoutReturnTypeを実装し、逆変換でメンバー関数の定義を出力するときにコンストラクターでもデストラクターでもない場合にのみ返り値型を出力するようにした。
正変換側ではなく逆変換側で対応したのは、ある関数型に対応する関数がコンストラクターまたはデストラクターであるかを、データ型をtypeTableに登録するタイミング(TypeTableInfo::registerType)で判定することが難しいため。
定義を伴わない宣言(例: `class A { A(int i, int j); };`)については未対応。
=> Don't emit return type when parsing constructor / destructor definition

XcodeMLtoCXX/src/AttrProc.h, XcodeMLtoCXX/src/ClangClassHandler.cpp, XcodeMLtoCXX/src/ClangClassHandler.h, XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/StringTree.cpp, XcodeMLtoCXX/src/StringTree.h, XcodeMLtoCXX/src/SymbolBuilder.cpp
[clang::CXXTemporaryObjectExpr](https://clang.llvm.org/doxygen/classclang_1_1CXXTemporaryObjectExpr.html)の逆変換に対応した。例:
```
// class X { X(int i, int j); };
X x = X(100, 200);
```
clang::CXXTemporaryObjectExprを逆変換で扱うために、 20e34cf71ae30c7ba29ce1d81b12babfd633d40c 以降放置されていたClangStmtHandlerをもう一度使うようにした。
仕様で定められていないが逆変換で対応しなければならない要素は今後ClangStmtHandlerで扱う。
=> Use ClangStmtHandler in CodeBuilder

CXXtoXML/src/NnsTableInfo.cpp, CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, XcodeMLtoCXX/src/ClangClassHandler.cpp, XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/Makefile, XcodeMLtoCXX/src/NnsAnalyzer.cpp, XcodeMLtoCXX/src/NnsAnalyzer.h, XcodeMLtoCXX/src/SourceInfo.h, XcodeMLtoCXX/src/SymbolAnalyzer.cpp, XcodeMLtoCXX/src/SymbolBuilder.cpp, XcodeMLtoCXX/src/XcodeMLtoCXX.cpp, XcodeMLtoCXX/src/XcodeMlNns.cpp, XcodeMLtoCXX/src/XcodeMlNns.h
* 正変換への入力プログラムで使われているnested-name-specifierについて、NNS識別名を発行しnnsTableに登録する
* XcodeMl::Nnsクラスとその派生クラスを定義する
* 逆変換において、nns属性が与えられているname要素に対してnested-name-specifierを付けた名前を出力する
=> Add support for nested-name-specifier to CXXtoXML/XcodeMLtoCXX

CXXtoXML/src/DeclarationsVisitor.cpp, CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, XcodeMLtoCXX/src/CodeBuilder.cpp, tests/Compilability/member_access.src.cpp
~`a->b` に対して~
```
<arrowExpr member="b">
<Var>a</Var>
</arrowExpr>
```
~を出力する。~
~この挙動はC_Frontとは異なる。~
=> Modify `a.b` to `&(a)->b` by XSLT

CXXtoXML/src/DeclarationsVisitor.cpp, XcodeMLtoCXX/src/CodeBuilder.cpp
クラス定義に対して、clangが有効なアクセス指定のない暗黙のclang::Declを挿入することがあり、逆変換のエラーの原因になります。これは逆変換がclassDecl要素の全ての子要素にaccess属性が与えられていることを期待しているためです。例：
```
class A {
// ここに `CXXRecordDecl 0x....... parent class B` が挿入される
class B* ptr;
};
```
一時的な処置として、逆変換においてaccess属性のないclassDeclの子要素を無視します。
=>  Ignore class member with no access specifier in XcodeMLtoCXX

XcodeMLtoCXX/src/CodeBuilder.cpp
宣言の初期化子として空の括弧式を用いることはできません。例：
```
X a(); // X型のオブジェクトではなくX型の返り値をもつ関数を宣言している
```
代わりに以下のように出力します。
```
X a;
```
=> Don't emit empty parenthesis for the initializer of a declarator

tests/CCTest/Makefile, tests/CCTest/examine.sh, tests/CCTest/stddef.h, tests/CCTest/stdio.h, tests/CCTest/stdlib.h
tests/CCTest ディレクトリの中だけでテストが完結できるようにしました。
* make build
CXXtoXML と XcodeMLtoCXX をリビルドします。
* make prepare-cpptest
… ../../../CppTest.tar.gz があるものだとして、それを CCTest/ 内の CppTest/ として展開し、
そこから *.src.cpp を作成します。 (main は int main にする)
* make check-cpptest
従来の check.sh の動きをします。ただし動作中に標準出力「にも」 CSV を吐きます。
補助スクリプトとして check.sh の examine() 関数と print_line() 関数の動きをする examine.sh を使います。
* make clean-cpptest
CCTest/ 内の CppTest/ ディレクトリがあれば、そこから作成されたと考えられる .src.cpp, .xml, .xcodeml,  .dst.cpp と .out を削除し、 err.log, result.csv も削除し、 CppTest/ ディレクトリも消します。
Makefile 中の install-cc は削除しました。
また、 check.sh は不要になります（が、念のため残してあります）。
=> add "make prepare-cpptest", "make check-cpptest", "make clean-cpptest" and "make build"

CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl
Fix `xsl:template[@match="clangConstructorInitializer"]`.
If a `clangConstructorInitializer` represents a base class initializer, the first child element of it is not `clangStmt` but `TypeLoc`.
Example:
```
class A {
public:
A(int, int);
};
class B : public A {
B(int i) : A(i, i), num(i) { }
int num;
};
```
```
- clangDecl[@class="CXXConstructor"] (B::B)
- name (B)
- clangDeclarationNameInfo (B)
- TypeLoc (void(int))
- TypeLoc (void)
- clangDecl[@class="ParmVar"]
- name (i)
- TypeLoc (int)
- clangConstructorInitializer (A(i, i))
- *TypeLoc* (A)
- clangStmt[@class="CXXConstructExpr"]
- clangStmt[@class="ImplicitCastExpr"]
- clangStmt[@class="DeclRefExpr"]
- clangDeclarationNameInfo (i)
- clangStmt[@class="ImplicitCastExpr"]
- clangStmt[@class="DeclRefExpr"]
- clangDeclarationNameInfo (i)
- …
```
=> Specify the target of xsl:template application in Program2XcodeProgram.xsl

CXXtoXML/src/DeclarationsVisitor.cpp, CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, XcodeMLtoCXX/src/CodeBuilder.cpp
[無名union](https://ezoeryou.github.io/cpp-book/C++11-Syntax-and-Feature.xhtml#anonymous_union)のメンバーへのアクセスを表現する要素がXcodeMLに存在しなかったので、xcodemlAccessToAnonRecordExpr要素を追加して対応しました。
=> Emit "xcodemlAccessToAnonRecordExpr" elements

tests/CCTest/stddef.h
=> Remove definition of wchar_t

CXXtoXML/src/DeclarationsVisitor.cpp, CXXtoXML/src/Makefile, CXXtoXML/src/TypeTableInfo.cpp, CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, CXXtoXML/src/XcodeMlNameElem.cpp, CXXtoXML/src/XcodeMlNameElem.h
name要素を新しく作る処理がTypeTableInfoとDeclarationsVisitorとの間で重複していたので一個にまとめた。
今後name要素の仕様が変更されたときに困らないようにする。
=> Add XcodeMlNameElem to CXXtoXML

CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, XcodeMLtoCXX/src/ClangClassHandler.cpp, XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/Makefile, XcodeMLtoCXX/src/XcodeMlName.cpp, XcodeMLtoCXX/src/XcodeMlName.h
* `memberFunctionCall` 要素を定義した
* `memberRef` 要素の代替として `memberExpr` 要素を定義した
* 逆変換でC++の名前を綺麗に扱うためのクラスとして `XcodeMl::UnqualId` とその派生クラス群を定義した (XcodeMLtoCXX/src/XcodeMlName.h)
* 正・逆変換を `memberFunctionCall`、`memberExpr` 要素に対応させた
メンバー関数としての演算子関数には対応していないが、これらの変更がmasterに取り込まれたあと別のブランチで対応する。
=> Add more support for member function call

CXXtoXML/src/DeclarationsVisitor.cpp, CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/LibXMLUtil.cpp, XcodeMLtoCXX/src/LibXMLUtil.h
`memberFunctionCall`要素 は廃止し、`memberFunction`要素をもつ`functionCall`要素で表現するようにした。
構文：
```
<functionCall>
<memberFunction>
memberExpr要素 (or memberPointerExpr要素)
</memberFunction>
<arguments>
0個以上の式の要素
</arguments>
</functionCall>
```
`memberExpr` 要素の構文を次のように変更した。
```
<memberExpr>
式の要素
名前の要素(<name> or <operator> or <conversion> or <constructor> or <destructor>)
</memberExpr>
```
以上の機能を正・逆変換に実装した。
=> Redesign `memberExpr` & `functionCall`

docs/XcodeML_CXX.md
> # 7.5 pointerRef要素
>式(ポインタ型またはリファレンス型)の指示先を表現する。
>`<pointerRef>`
>  式の参照
>`</pointerRef>`
で、"式の参照" を "式の要素" に変更した。
=> Correct {#sec:expr.pointer}

XcodeMLtoCXX/src/CodeBuilder.cpp
* 使われなくなった関数を削除した
* staticキーワードを無名名前空間で置き換えた
* ファイルの外に漏れていた名前をファイルローカルにした
=> Clean CodeBuilder.cpp

CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, XcodeMLtoCXX/src/ClangClassHandler.cpp, XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/StringTree.cpp, XcodeMLtoCXX/src/StringTree.h
```
int a[3] = { 0, 1, 2 };
```
の `{ 0, 1, 2 }` などの式は `value` 要素で表現するが、これを正・逆変換に実装した。
=> Add support for `value` elements as aggregates

CXXtoXML/src/Makefile
`make LLVM_INCLUDE=/path/to/include` でディレクトリを指定します。
=> Use `llvm-config --includedir` in Makefile

XcodeMLtoCXX/src/XcodeMlOperator.cpp
Ref: [{#sec:expr.assign}](https://github.com/omni-compiler/ClangXcodeML/blob/b119953cf94f9430ef49292d9824f2df7b57448e/docs/XcodeML_CXX.md#assignexpr-%E8%A6%81%E7%B4%A0-secexprassign)
=> Register `assignExpr` with opMap in XcodeMlOperator.cpp

XcodeMLtoCXX/src/XcodeMlOperator.cpp
Update /XcodeMLtoCXX/src/XcodeMlOperator.cpp.
Add "newExpr", "newArrayExpr", "deleteExpr", "deleteArrayExpr" to `opMap`(`const std::map<std::string, std::string>`).
=> Add allocation/deallocation operators to XcodeMlOperator

scripts/CXXtoXcodeML
This reverts commit e18fe52aee2e82d128edc35342fbd45a29959eea.
`xmllint --format` is better than `xsl:output/@indent`.
=> Revert "Remove an unnecessary command in CXXtoXcodeML"

XcodeMLtoCXX/src/AttrProc.h
`AttrProc` クラステンプレートのコンストラクターが悪かったので修正した。
=> Rewrite constructors of `AttrProc`

XcodeMLtoCXX/src/CodeBuilder.cpp
Fix CodeBuilder.cpp.
`std::move` suppress optimization (copy elision).
=> Don't use `std::move` on return value

CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, CXXtoXML/src/XSLTs/add_symbols_elem.xsl, XcodeMLtoCXX/src/CodeBuilder.cpp
逆変換がXSLTの生成するparams要素の存在に依存していたので修正した。
=> Get parameter nodes from `TypeLoc/clangDecl[@class='ParmVar']`

XcodeMLtoCXX/src/CodeBuilder.cpp
変換関数の宣言には返り値型を書くことが出来ません。例: `int X::operator int();`
=> Don't emit the return type of conversion functions

CXXtoXML/src/DeclarationsVisitor.cpp
`InitListExpr` has two kinds of children, `SyntacticForm` and
`SemanticForm`.
> // This method is called once for each pair of syntactic and semantic
> // InitListExpr, and it traverses the subtrees defined by the two forms. This
> // may cause some of the children to be visited twice, if they appear both in
> // the syntactic and the semantic form.
(/clang/include/clang/AST/RecursiveASTVisitor.h)
By default, `RecursiveASTVisitor` traverses both of them, therefore,
`DeclarationsVisitor` emits the elements of initializer lists twice.
Example:
Input: `a[3] = { 1, 2, 3 };`
Output: `a[3] = { 1, 2, 3, 1, 2, 3 };`
This commit solves the problem.
Update `DeclarationsVisitor::PreVisitStmt(S)`.
If `S` is an `InitListExpr`, then manually traverse the children of `S`
and return `false` to suppress …
=> Traverse children of `InitListExpr` only once

XcodeMLtoCXX/src/ClangClassHandler.cpp
逆変換で、クラスの前方宣言を出力する前にクラス名を登録するのを忘れていた。
=> Set class name before emitting forward declaration

CXXtoXML/src/Makefile, XcodeMLtoCXX/src/Makefile, XcodeMLtoCXX/tests/UnitTest/Makefile
Update /CXXtoXML/src/Makefile.
Update /XcodeMLtoCXX/src/Makefile.
Update /XcodeMLtoCXX/tests/UnitTest/Makefile.
Define `PKG_CFLAGS` and `PKG_LIBS`.
```
PKG_CFLAGS = $(shell pkg-config --cflags libxml-2.0 2>/dev/null || echo -I/usr/include/libxml2)
PKG_LIBS = $(shell pkg-config --libs libxml-2.0 2>/dev/null || echo -lxml2)
```
As a result, the test environments do not need `pkg-config`.
=> Introduce `PKG_CFLAGS` and `PKG_LIBS` to Makefile

XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/TypeAnalyzer.cpp, XcodeMLtoCXX/src/XcodeMlType.cpp, XcodeMLtoCXX/src/XcodeMlType.h
関数宣言中のデフォルト実引数に対応するために、まず関数型を表現する `XcodeMl::Function` のまわりの悪い命名を直しました。
=> Fix wrong naming convention

XcodeMLtoCXX/src/ClangClassHandler.cpp, XcodeMLtoCXX/src/LibXMLUtil.cpp, XcodeMLtoCXX/src/Stream.cpp, XcodeMLtoCXX/src/Stream.h, XcodeMLtoCXX/src/StringTree.cpp, XcodeMLtoCXX/src/SymbolBuilder.cpp, XcodeMLtoCXX/src/XcodeMlType.cpp, XcodeMLtoCXX/tests/UnitTest/CXXCodeGenStream.cpp
`CXXCodeGen::Stream` はXcodeMLtoCXX/で定義されたクラスで、C++プログラムを実際に文字列として生成する役割を持つ。
今回 `#line` ディレクティブを実装することになったので、 `Stream` クラスにファイル名と行番号を記憶するためのメンバーを追加することにした。
ところで、このようなことは今後も起こりうる。つまり、C++プログラムをある決まった書式で出力したいという要望は今後も出てきそう。その場合 `CXXCodeGen::Stream` のデータメンバーが増えていくと考えられるので、クライアントの再コンパイルや `#include` の追加を防ぐために `Stream` クラスをPimplイディオムで書き直した。
細かい点についてはコミットメッセージを参照してください。
=> Reimplement `CXXCodeGen::Stream` by Pimpl

CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, XcodeMLtoCXX/src/ClangClassHandler.cpp, XcodeMLtoCXX/src/CodeBuilder.cpp
Update Program2XcodeProgram.xsl.
Update ClangClassHandler.cpp.
Update CodeBuilder.cpp.
The `TypeLoc` element was renamed to `clangTypeLoc` on the commit
7cf73588f03bc49522b7c163d3e02fab16faeb4f.
I forgot to update files that use this element.
=> Search for `clangTypeLoc` instead of `TypeLoc`

CXXtoXML/src/CXXtoXML.cpp, CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, CXXtoXML/src/XSLTs/add_globalsymbols_elem.xsl, docs/ClangXML.md
Update CXXtoXML.cpp.
Remove `clangAST`, an unnecessary wrapper element.
Pass `nullptr` instead of `"clangAST"` to the constructor of `XMLVisitorBase` as the `ChildName` parameter.
```
explicit XMLVisitorBase(clang::MangleContext *MC,
xmlNodePtr Parent,
const char *ChildName,
TypeTableInfo *TTI = nullptr,
NnsTableInfo *NTI = nullptr)
: XMLVisitorBaseImpl(MC,
(ChildName ? xmlNewTextChild(
Parent, nullptr, BAD_CAST ChildName, nullptr)
: Parent),
TTI,
NTI),
optContext(){};
```
([/CXXtoXML/src/XMLVisitorBase.h](https://github.com/omni-compiler/ClangXcodeML/blob/master/CXXtoXML/src/XMLVisitorBase.h#L65))
=> Do not emit `Program` element

CXXtoXML/src/DeclarationsVisitor.cpp, CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, XcodeMLtoCXX/src/ClangClassHandler.cpp, tests/Compilability/define_constant.src.cpp, tests/Compilability/overload_int_char.src.cpp
* 正変換コアを更新して、 `clangStmt`要素の`token`属性が正しい値をもつようにした
* 整数リテラルの接尾辞をちゃんと保存して、リテラルの型が正変換→逆変換の過程で保たれるようにした。文字リテラルも同様
* Program2XcodeProgram.xslのテンプレートルールの数を減らした
* テストケースを追加した
=> Preserve types of literals

CXXtoXML/src/CXXtoXML.cpp
正変換コアで、C++プログラムに対する出力の`language`属性を`"C++"`にした。
=> Emit `clangAST/@language[.='C++']`

CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/SourceInfo.h
逆変換を更新して, C++に対してのみ言語リンケージ宣言 `extern "C"`, `extern "C++"` を出力するようにした.
=> Don't emit language linkage declarations if the source language is C

XcodeMLtoCXX/src/ClangClassHandler.cpp, XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/LibXMLUtil.cpp, XcodeMLtoCXX/src/LibXMLUtil.h, XcodeMLtoCXX/src/Makefile, XcodeMLtoCXX/src/SourceInfo.cpp, XcodeMLtoCXX/src/SourceInfo.h, tests/Compilability/unnamed_class.src.cpp, tests/Compilability/unnamed_class_with_multi_vars.src.cpp
* テストケースを追加した
* 逆変換で、無名クラスに`__xcodeml_1`のような名前を付けて復元するようにした
はじめ、無名クラスを無名クラスのまま復元するよう試みましたが、色々問題があり諦めました(f7357097b5353c41e0e9bec3a23221d7ff7e34e8)。
=> Add names to unnamed classes

XcodeMLtoCXX/src/XcodeMlOperator.cpp, tests/Compilability/operator_decrement.src.cpp, tests/Compilability/operator_increment.src.cpp
逆変換で、インクリメント/デクリメント演算子を `opMap` に追加するのを忘れていたので追加した。
=>  Add increment/decrement operators to `opMap` 

CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, XcodeMLtoCXX/src/ClangClassHandler.cpp, XcodeMLtoCXX/src/ClangClassHandler.h, XcodeMLtoCXX/src/CodeBuilder.cpp, tests/Compilability/templ_func_explicit_templ_arg.src.cpp
逆変換を更新して, 明示的に指定された関数テンプレートのテンプレート実引数 (例: `func<int, int>()`) を復元するようにした.
=> Emit explicitly-specified function template arguments

CXXtoXML/src/DeclarationsVisitor.cpp, CXXtoXML/src/NnsTableInfo.cpp, CXXtoXML/src/NnsTableInfo.h, tests/Compilability/various_decl_context.src.cpp
正変換を更新して、 `name`要素が`test_nns`属性および`test_nns_decl_kind`属性を持つようにしました。詳細については各コミットメッセージを参照してください。
`test_nns`属性および`test_nns_decl_kind`属性は暫定的なものであり、今後変更されます。しかしこのままmasterに取り込んでも特に害はないので、diffがこれ(+128, -29)以上大きくなることを避けるために今の状態でプルリクエストを出します。
=> Emit `name/@test_nns`, `name/@test_nns_decl_kind`

XcodeMLtoCXX/src/Stream.cpp, XcodeMLtoCXX/tests/UnitTest/CXXCodeGenStream.cpp
Update XcodeMLtoCXX/src/Stream.cpp.
Rewrite `shouldInterleaveSpace(char, char)` and emit spaces (' ') before
emitting colons (':') in output C++ program.
Example 1:
label1:::i = 1;  // error
label1: ::i = 1; // OK
~Example 2:~
~void::Class1::func() { }  // error~
~void ::Class1::func() { } // OK~
=> Emit spaces before colons (XcodeMLtoCXX)

tests/compile/class_templ_decl.src.cpp
```
tempalte<typename T> class ClassA {
```
=> Fix typo in tests/compile/class_templ_decl.src.cpp

CXXtoXML/src/TypeTableInfo.cpp, tests/compile/recursive_struct.src.cpp, tests/compile/recursive_struct_reference.src.cpp
Problem: CXXtoXML aborts when the input C/C++ program has a struct declaration (hereinafter referred to as `struct B`) that has a member of pointer-to-struct-B type, and another struct that is declared before the declaration of `struct B` (hereinafter referred to as `struct A`) also has a member of pointer-to-struct-B type, e.g.
struct A {
struct B *ptr1;
};
struct B {
struct B *ptr2;
};
Solution: Change the order of procedures in `TypeTableInfo::registerType`, and apply `TypeTableInfo::registerPointerType` to type `T` before applying `TypeTableInfo::registerType` to `clang::dyn_cast<const clang::PointerType>(T.getTypePtr())->getPointeeType()`.
=> Call `registerPointerType` for type `T` before registering its pointee type in TypeTableInfo

XcodeMLtoCXX/src/ClangDeclHandler.cpp, XcodeMLtoCXX/src/CodeBuilder.cpp, tests/run/constructor.src.cpp
逆変換がメンバー初期化子リストを無視するようになっていたので修正しました。
=> Emit member initializer lists

CXXtoXML/src/TypeTableInfo.cpp, CXXtoXML/src/XcodeMlNameElem.cpp, CXXtoXML/src/XcodeMlNameElem.h, XcodeMLtoCXX/src/ClangDeclHandler.cpp, XcodeMLtoCXX/src/TypeAnalyzer.cpp, XcodeMLtoCXX/src/XcodeMlType.cpp, XcodeMLtoCXX/src/XcodeMlType.h
There are two types of `clang::TemplateTypeParmType` objects; canonical and non-canonical. A non-canonical `TemplateTypeParmType` has a pointer to a `clang::TeplateTypeParmDecl`. A canonical `TemplateTypeParmType` does not have such a pointer, but it has two `unsigned` numbers; `index` and `depth`.
// include/clang/AST/Type.h
class TemplateTypeParmType : public Type, public llvm::FoldingSetNode {
// Helper data collector for canonical types.
struct CanonicalTTPTInfo {
unsigned Depth : 15;
unsigned ParameterPack : 1;
unsigned Index : 16;
};
union {
// Info for the canonical type.
CanonicalTTPTInfo CanTTPTInfo;
// Info for the non-canonical type.
TemplateTypeParmDecl *TTPDecl;
};
We can retrieve canonical `TemplateTypeParmType`s from non-canonical ones, but the reverse is not true.
We …
=> Don't use TemplateTypeParm::setSpelling 

XcodeMLtoCXX/src/XcodeMlType.cpp, XcodeMLtoCXX/src/XcodeMlType.h, tests/run/array.src.cpp, tests/run/array_to_cv_qual_type.src.cpp
```diff
@@ -388,7 +388,7 @@ Array::makeDeclaration(CodeFragment var, const Environment &env) {
: makeTokenNode("*");
const CodeFragment declarator = makeTokenNode("[")
+ (isConst() ? makeTokenNode("const") : makeVoidNode())
-      + (isConst() ? makeTokenNode("volatile") : makeVoidNode())
+      + (isVolatile() ? makeTokenNode("volatile") : makeVoidNode())
+ size_expression + makeTokenNode("]");
return makeDecl(elementType, var + declarator, env);
}
```
=> Fix typo in Array::makeDeclaration (XcodeMlType.cpp)

XcodeMLtoCXX/src/ClangDeclHandler.cpp, XcodeMLtoCXX/src/XMLWalker.h, XcodeMLtoCXX/src/XcodeMlName.cpp, XcodeMLtoCXX/src/XcodeMlName.h, XcodeMLtoCXX/src/XcodeMlUtil.cpp
ビットフィールドをサポートしました。
- ビットフィールドのビット長は式となりうるため TypeTable には持たない設計になってしまっているので、
FieldDecl として出力する歳に is_bit_field, is_unnamed_bit_field の属性（これは PR #305 で追加済み）を見て適切に処理するようにした
- 特に「無名ビットフィールド」をサポートするために、
XcodeMlType の ClassType が保持している classScopeSymbols の UnqualId 部に UnnamedId という種別を追加 (toString したら "" が返る)
の二点が主な変更点です。
また、もともと XMLWalker walk() で例外をキャッチしていたところで落ちていたので、
そこのデバッグ用のログの生成を少しだけ丁寧にしました。
=> support bit fields (including unnamed bit fields)

XcodeMLtoCXX/src/XcodeMlType.cpp
handle the case like "int (*p)[10]" properly.
=> always surround pointer type declarations like "int (*p);"
