XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/CodeBuilder.h
Example
```
void f()
{
do      {
}
while (0);
}
void f()
{
while (1)
{
{
int i = 1;
}
}
}
```
=> Indentation

XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/CodeBuilder.h, XcodeMLtoCXX/src/Makefile, XcodeMLtoCXX/src/SymbolAnalyzer.h, XcodeMLtoCXX/src/TypeAnalyzer.cpp, XcodeMLtoCXX/src/TypeAnalyzer.h, XcodeMLtoCXX/src/XcodeMLtoCXX.cpp, XcodeMLtoCXX/src/XcodeMlType.cpp, XcodeMLtoCXX/src/XcodeMlType.h
typeTable 部のうち、とくに structType についてまともな情報を生成できるようにしようとしている最中のブランチ。ブランチしたままだとやりづらいのでいったん master に取り込み。
=> developping branch to implement <typeTable> processor

XcodeMLtoCXX/Makefile, XcodeMLtoCXX/src/XcodeMlType.cpp, XcodeMLtoCXX/src/XcodeMlType.h, XcodeMLtoCXX/tests/UnitTest/XcodeMlType.cpp
別の開発ブランチでTypeのダウンキャストが必要になりました。
=> LLVM-style RTTI for XcodeMl::Type

XcodeMLtoCXX/src/AttrProc.h, XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/CodeBuilder.h, XcodeMLtoCXX/src/LibXMLUtil.cpp, XcodeMLtoCXX/src/LibXMLUtil.h, XcodeMLtoCXX/src/Makefile, XcodeMLtoCXX/src/SourceInfo.h, XcodeMLtoCXX/src/Symbol.h, XcodeMLtoCXX/src/SymbolAnalyzer.cpp, XcodeMLtoCXX/src/SymbolAnalyzer.h, XcodeMLtoCXX/src/SymbolBuilder.cpp, XcodeMLtoCXX/src/SymbolBuilder.h, XcodeMLtoCXX/src/SymbolsBuilder.cpp, XcodeMLtoCXX/src/SymbolsBuilder.h, XcodeMLtoCXX/src/TypeAnalyzer.cpp, XcodeMLtoCXX/src/XMLString.cpp, XcodeMLtoCXX/src/XMLString.h, XcodeMLtoCXX/src/XcodeMLtoCXX.cpp, XcodeMLtoCXX/src/XcodeMlEnvironment.cpp, XcodeMLtoCXX/src/XcodeMlEnvironment.h, XcodeMLtoCXX/src/XcodeMlType.cpp, XcodeMLtoCXX/src/XcodeMlType.h, XcodeMLtoCXX/tests/Compilability/Makefile, XcodeMLtoCXX/tests/Makefile, XcodeMLtoCXX/tests/UnitTest/Makefile, XcodeMLtoCXX/tests/UnitTest/XcodeMlType.cpp
このPull Requestは以下の変更を含みます。
* 配列の要素数を出力するようにした
* array_size属性のみ。arraySize要素が使われている場合については未対応
* 配列のCV修飾子に対応した
* (C-style)構造体の定義を出力するようにした
* 関数宣言の出力方法が間違っていたので修正した
=> Improve XcodeMLtoCXX

CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, CXXtoXML/src/XSLTs/add_symbols_elem.xsl
/CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl を追加した。
```
./CXXtoXML src.cpp -- | xsltproc add_symbols_elem.xsl - > dst.cpp
```
のように使う。
=> Add <symbols>/<globalSymbols> to CXXtoXML output

CXXtoXML/src/CXXtoXML.cpp, CXXtoXML/src/DumpTypeTable.cpp, CXXtoXML/src/DumpTypeTable.h, CXXtoXML/src/Makefile, CXXtoXML/src/TypeTableVisitor.cpp, CXXtoXML/src/TypeTableVisitor.h
```
$ ./CXXtoXML -dump-typeTable sample.cpp --
Pointer0: int *
Function0: int (int)
int: int
```
=> Add -dump-typeTable option to CXXtoXML

XcodeMLtoCXX/src/CXXCodeGen.cpp, XcodeMLtoCXX/src/CXXCodeGen.h, XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/Makefile, XcodeMLtoCXX/src/SourceInfo.h, XcodeMLtoCXX/src/SymbolBuilder.cpp, XcodeMLtoCXX/tests/UnitTest/Makefile
CXXCodeGen::Streamクラスを定義して空気を読んでスペースやインデントを入れるようにした
=> Make XcodeMLtoCXX emit pretty-formatted C++ codes

XcodeMLtoCXX/src/CXXCodeGen.cpp, XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/tests/UnitTest/CXXCodeGenStream.cpp, XcodeMLtoCXX/tests/UnitTest/Makefile
* UnitTest/Makefile を修正
* `CXXCodeGen::Stream` 用のテストを追加
* CXXCodeGen::Streamのバグを修正
=> Add UnitTest/CXXCodeGenStream.cpp

CXXtoXML/src/ClangUtil.cpp, CXXtoXML/src/ClangUtil.h, CXXtoXML/src/DeclarationsVisitor.cpp, CXXtoXML/src/Makefile
* `language_linkage`属性
* `linkage`属性
* `clang_linkage_internal`属性
=> Emit more attributes from CXXtoXML

docs/XcodeML_CXX.md
\<class\>要素を\<classType\>要素に変更します。
=> Rename: <class> -> <classType>

XcodeMLtoCXX/src/CodeBuilder.cpp
未実装の二項演算子・前置単項演算子・ if 文を実装。
後置単項演算子と3項演算子は未着手。
=> XcodeMLtoCXX/src/CodeBuilder.cpp: implement operators, if-statement

XcodeMLtoCXX/src/TypeAnalyzer.cpp, XcodeMLtoCXX/src/XcodeMlType.cpp, XcodeMLtoCXX/src/XcodeMlType.h
詳細については fe2b82711303b71a7b6fed75f7f0644bbd1a945a を見てください
=> Use XcodeMl::QualifiedType for  <basicType> in XcodeMLtoCXX

CXXtoXML/src/CXXtoXML.cpp, CXXtoXML/src/DeclarationsVisitor.cpp, CXXtoXML/src/Makefile, CXXtoXML/src/NnsTableInfo.cpp, CXXtoXML/src/NnsTableInfo.h, CXXtoXML/src/XMLVisitorBase.cpp, CXXtoXML/src/XMLVisitorBase.h, CXXtoXML/src/XSLTs/add_globalsymbols_elem.xsl
* NnsTableInfoを追加した
* `<classNNS>`を出力するようにした
=> Emit <nnsTable>

XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/XcodeMlType.cpp, XcodeMLtoCXX/src/XcodeMlType.h
逆変換で`<functionDecl>`によるコンストラクター・デストラクターの宣言に対応した
Ref: #93
=> Support constructor / destructor declaration

CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, tests/CCTest/Makefile
=> Handle declaration statements that have several declarations

CXXtoXML/src/DeclarationsVisitor.cpp, XcodeMLtoCXX/src/ClangClassHandler.cpp, XcodeMLtoCXX/src/CodeBuilder.cpp
例：
```
extern "C" { void func(); }
```
=> Handle linkage specifications

CXXtoXML/src/DeclarationsVisitor.cpp, CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, CXXtoXML/src/XSLTs/add_globalsymbols_elem.xsl, XcodeMLtoCXX/src/CodeBuilder.cpp
classDecl要素のis_this_declaration_a_definition属性が真のときにのみクラス定義を出力する
=> Handle class forward declaration

CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, XcodeMLtoCXX/src/CodeBuilder.cpp
* XSLT(Program2XcodeProgram.xsl)
* `clangStmt[@class='SwitchStmt']`
* `clangStmt[@class='CaseStmt']`
* `clangStmt[@class='DefaultStmt']`
* XcodeMLtoCXX
* switchStatementProc
* caseLabelProc
* defaultLabelProc
=> Handle switch statements

CXXtoXML/src/DeclarationsVisitor.cpp, CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, XcodeMLtoCXX/src/CodeBuilder.cpp
```
class Base {
int f();
};
class Derived : Base {
Base::f; // access declaration
};
```
=> Handle access declaration

CXXtoXML/src/TypeTableInfo.cpp, XcodeMLtoCXX/src/TypeAnalyzer.cpp, XcodeMLtoCXX/src/XcodeMlType.cpp, XcodeMLtoCXX/src/XcodeMlType.h
functionType要素のis_const, is_volatile属性によってメンバー関数に与えられたqualifierを表現する。
=> Hanfle constness and volatility of member functions

CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, XcodeMLtoCXX/src/CodeBuilder.cpp, XcodeMLtoCXX/src/LibXMLUtil.cpp, XcodeMLtoCXX/src/LibXMLUtil.h
=> Add "nns" attribute to "Var" element

docs/CXXtoXML-src.md
=> Add /docs/CXXtoXML-src.md

CXXtoXML/src/XSLTs/Program2XcodeProgram.xsl, CXXtoXML/src/XSLTs/add_globalsymbols_elem.xsl, CXXtoXML/src/XSLTs/add_symbols_elem.xsl, CXXtoXML/src/XSLTs/drop_prop_column.xsl, CXXtoXML/src/XSLTs/drop_prop_file.xsl, CXXtoXML/src/XSLTs/drop_prop_lineno.xsl, CXXtoXML/src/XSLTs/handle_name_elem.xsl, CXXtoXML/src/XSLTs/reorder_decl.xsl, scripts/CXXtoXcodeML
参照：https://triple-underscore.github.io/XML/xslt10-ja.html#output
=>  Set `xsl:output/@indent` to "yes" in CXXtoXML

CXXtoXML/src/XMLVisitorBase.cpp
=> Don't use xmlStrPrintf

XcodeMLtoCXX/src/NnsAnalyzer.cpp, XcodeMLtoCXX/src/SymbolBuilder.cpp, tests/Compilability/member_access.src.cpp
=> (miscellaneous changes)

schema/XcodeML_CXX.rnc
RELAX NGで文法を記述した。
XcodeML_CXX.xsdは将来削除します。
=> Add XcodeML_CXX.rnc

XcodeMLtoCXX/src/LibXMLUtil.cpp, XcodeMLtoCXX/src/LibXMLUtil.h, XcodeMLtoCXX/src/Makefile, XcodeMLtoCXX/src/XcodeMlUtil.cpp, XcodeMLtoCXX/src/XcodeMlUtil.h
=> Add XcodeMlUtil to /XcodeMLtoCXX/src/

XcodeMLtoCXX/src/XcodeMlName.cpp
変更の詳細については各コミットメッセージを参照してください。
=> Fix `XcodeMl::DtorName`

XcodeMLtoCXX/src/Stream.cpp, XcodeMLtoCXX/src/Stream.h
=> Rewrite `CXXCodeGen::Stream`

tests/CCTest/stdlib.h
=> Fix language linkage

tests/CCTest/Makefile, tests/Compilability/Makefile
Update /tests/CCTest/Makefile.
Update /tests/Compilability/Makefile.
=> Define `make clangxml`

docs/ClangXML.md
Ref: commit 3e7b2b9a06edff6e949ffb14a082042656a623ee
=> Add description of attributes of `clangAST`

CXXtoXML/src/TypeTableInfo.cpp
=> Introduce commonSetUpForRecordDecl

CXXtoXML/src/DeclarationsVisitor.cpp, CXXtoXML/src/TypeTableInfo.cpp, CXXtoXML/src/XMLVisitorBase.cpp, CXXtoXML/src/XcodeMlNameElem.cpp
new properties:
- is_bit_field  (for FieldDecl)
- is_unnamed_bit_field  (for FieldDecl)
- is_first_decl  (for Decl)
- is_canonical_decl  (for Decl)
=> suppress to emit properties is_XXX="0" (has_XXX="0"). add some new is_* property.

CXXtoXML/src/NnsTableInfo.cpp, XcodeMLtoCXX/src/NnsAnalyzer.cpp, XcodeMLtoCXX/src/XcodeMlNns.cpp, XcodeMLtoCXX/src/XcodeMlNns.h, tests/run/unnamed_namespace.src.cpp
=> Handle unnamed namespace correctly

XcodeMLtoCXX/src/ClangStmtHandler.cpp, tests/run/functional_notation_with_nested_name_spec.src.cpp
=> Improve explicit-type-conversion support

XcodeMLtoCXX/src/ClangStmtHandler.cpp, XcodeMLtoCXX/src/CodeBuilder.cpp
such as:
in constructor-initializer-list: ClassX() : Base(Base(...))
Materialization
ReturnStmt with a copy constructor
=> unwrap impeditive copy(or move) constructors
